# Generated by Django 5.2.4 on 2025-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "changge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machinereport",
            name="filename",
        ),
        migrations.AddField(
            model_name="machinereport",
            name="mac",
            field=models.CharField(
                db_index=True, default="00-00-00-00-00-00", max_length=64
            ),
            preserve_default=False,
        ),
    ]
