# Generated by Django 5.2.4 on 2025-07-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MachineReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=20)),
                ("cpu", models.CharField(max_length=64)),
                ("kernel", models.CharField(max_length=128)),
                ("os", models.CharField(max_length=64)),
                ("architecture", models.CharField(max_length=32)),
                ("vuln_count", models.PositiveIntegerField()),
                ("risk_count", models.PositiveIntegerField()),
                ("time", models.DateTimeField()),
            ],
            options={
                "db_table": "machine_report",
                "ordering": ["id"],
            },
        ),
    ]
