# Generated by Django 5.2.4 on 2025-07-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_remove_machinereport_filename_machinereport_mac"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machinereport",
            name="mac",
        ),
    ]
