# Generated by Django 5.2.4 on 2025-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_machinereport_mac"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinereport",
            name="ss",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
