# Generated by Django 5.2.4 on 2025-07-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_machinereport_ss"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machinereport",
            name="ss",
        ),
    ]
