# Generated by Django 5.2.4 on 2025-07-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_machinereport_ss"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceVulnSnapshot",
            fields=[
                (
                    "mac",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("cve_2017_5753", models.BooleanField(null=True)),
                ("cve_2017_5715", models.BooleanField(null=True)),
                ("cve_2017_5754", models.BooleanField(null=True)),
                ("cve_2018_3640", models.BooleanField(null=True)),
                ("cve_2018_3639", models.BooleanField(null=True)),
                ("cve_2018_3615", models.BooleanField(null=True)),
                ("cve_2018_3620", models.BooleanField(null=True)),
                ("cve_2018_3646", models.BooleanField(null=True)),
                ("cve_2018_12126", models.BooleanField(null=True)),
                ("cve_2018_12130", models.BooleanField(null=True)),
                ("cve_2018_12127", models.BooleanField(null=True)),
                ("cve_2019_11091", models.BooleanField(null=True)),
                ("cve_2019_11135", models.BooleanField(null=True)),
                ("cve_2018_12207", models.BooleanField(null=True)),
                ("cve_2020_0543", models.BooleanField(null=True)),
                ("cve_2023_20593", models.BooleanField(null=True)),
                ("cve_2022_40982", models.BooleanField(null=True)),
                ("cve_2022_4543", models.BooleanField(null=True)),
                ("cve_2023_20569", models.BooleanField(null=True)),
                ("cve_2023_23583", models.BooleanField(null=True)),
                ("extra_1", models.BooleanField(null=True)),
            ],
            options={
                "db_table": "device_vuln_snapshot",
            },
        ),
    ]
