# Generated by Django 5.2.4 on 2025-07-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_devicevulnsnapshot_infos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicevulnsnapshot",
            name="infos",
        ),
        migrations.RemoveField(
            model_name="devicevulnsnapshot",
            name="updated_at",
        ),
    ]
