# Generated by Django 5.2.4 on 2025-07-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_devicevulnsnapshot_infos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2017_5715_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2017_5753_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2017_5754_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_12126_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_12127_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_12130_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_12207_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3615_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3620_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3639_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3640_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3646_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2019_11091_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2019_11135_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2020_0543_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2022_40982_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2022_4543_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2023_20569_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2023_20593_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="devicevulnsnapshot",
            name="cve_2023_23583_info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
