# Generated by Django 5.2.4 on 2025-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_devicevulnsnapshot_cve_2017_5715_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2017_5715",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2017_5753",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2017_5754",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_12126",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_12127",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_12130",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_12207",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3615",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3620",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3639",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3640",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2018_3646",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2019_11091",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2019_11135",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2020_0543",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2022_40982",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2022_4543",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2023_20569",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2023_20593",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="devicevulnsnapshot",
            name="cve_2023_23583",
            field=models.BooleanField(null=True),
        ),
    ]
